export * from './components/Body';
export { default as Controller } from './components/Footer/Controller';
export { default as Footer } from './components/Footer/Footer';
export { default as FooterCard } from './components/Footer/FooterCard';
export * from './components/Footer/Icons';
export * from './components/Header';
export { default as AlanCard } from './components/PreFooter/AlanCard';
export { default as Prefooter } from './components/PreFooter/Prefooter';
export * from './components';
export { default as layout } from './layout';
export * from './Home';
